#!/usr/bin/env python3
"""
Turn the source asset pack into web-ready derivatives.

The pack ships ~1.8 MB PNGs at a single size. Shipping those to browsers would
cost ~40 MB on a page carrying twenty of them, so this converts each one into a
small set of WebP widths plus a dominant-colour swatch for the placeholder.

Deliberately run by hand, not at build time. The derivatives are committed, so
neither CI nor a contributor needs Python, Pillow, or the 158 MB of source in
order to build the site. Re-run it only when the pack changes.

    python3 tools/images/build-derivatives.py 02_HOSPITALITY

Source folders are the pack directories at the repository root. Output lands in
frontend/public/img/<slug>/ alongside a generated manifest the site imports.

10_REFERENCE_ONLY is refused outright: the pack marks it "DO NOT USE WITHOUT
REVIEW", and the cheapest way to honour that is to make it impossible to
publish by accident. See WEBSITE_PAGE_ASSET_MAP.md.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
OUT_ROOT = REPO / "frontend" / "public" / "img"
MANIFEST = REPO / "frontend" / "src" / "data" / "imageManifest.js"

# Widths chosen against the layout, not picked round: the vertical pages cap
# content at max-w-5xl (1024px), so 1600 covers a 2x tap on the largest card and
# 640 covers a phone. A fourth width earns nothing and costs a request.
WIDTHS = [640, 1024, 1600]
QUALITY = 76

REFUSED = {"10_REFERENCE_ONLY"}


def slugify(name: str) -> str:
    """café -> cafe. Filenames reach URLs, and a URL-encoded é is nobody's friend."""
    ascii_name = (
        unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    )
    ascii_name = re.sub(r"[^a-zA-Z0-9]+", "-", ascii_name).strip("-").lower()
    return re.sub(r"-+", "-", ascii_name)


def dominant_colour(im: Image.Image) -> str:
    """One averaged colour, used as the box background while the image loads.

    Cheaper than a blurred LQIP (no extra bytes at all — it lands in the
    manifest as a hex string) and enough to stop the page flashing white
    against a dark theme.
    """
    small = im.convert("RGB").resize((1, 1), Image.Resampling.LANCZOS)
    r, g, b = small.getpixel((0, 0))
    return f"#{r:02x}{g:02x}{b:02x}"


def build_folder(folder: str) -> list[dict]:
    if folder in REFUSED:
        sys.exit(
            f"refusing {folder}: the pack marks it REFERENCE ONLY — DO NOT USE "
            f"WITHOUT REVIEW. Publishing it needs a deliberate decision, not a "
            f"default."
        )

    src_dir = REPO / folder
    if not src_dir.is_dir():
        sys.exit(f"no such source folder: {src_dir}")

    slug = slugify(folder.split("_", 1)[1] if "_" in folder else folder)
    out_dir = OUT_ROOT / slug
    out_dir.mkdir(parents=True, exist_ok=True)

    entries = []
    for src in sorted(src_dir.glob("*.png")):
        stem = slugify(src.stem)
        with Image.open(src) as im:
            im = im.convert("RGB")
            w, h = im.size
            entry = {
                "id": stem,
                "src": f"/img/{slug}/{stem}-1024.webp",
                "width": w,
                "height": h,
                "colour": dominant_colour(im),
                "widths": [],
            }
            for target in WIDTHS:
                # Never upscale — a 1254px master has no 1600px detail to give,
                # and inventing pixels only inflates the file.
                if target > w:
                    continue
                ratio = target / w
                resized = im.resize(
                    (target, round(h * ratio)), Image.Resampling.LANCZOS
                )
                dest = out_dir / f"{stem}-{target}.webp"
                resized.save(dest, "WEBP", quality=QUALITY, method=6)
                entry["widths"].append(target)

            if not entry["widths"]:
                sys.exit(f"{src.name}: {w}px is narrower than every target width")

            # Point src at the largest width actually produced, so a 1254px
            # master does not advertise a 1600px file that was never written.
            largest = entry["widths"][-1]
            entry["src"] = f"/img/{slug}/{stem}-{largest}.webp"
            entries.append(entry)

    return entries


def write_manifest(all_entries: dict[str, list[dict]]) -> None:
    body = json.dumps(all_entries, indent=2, sort_keys=True)
    MANIFEST.write_text(
        "// Generated by tools/images/build-derivatives.py — do not edit by hand.\n"
        "//\n"
        "// Maps each image to the widths that actually exist on disk plus a\n"
        "// dominant colour, so <Figure> can emit a correct srcset and reserve\n"
        "// the right box before the image arrives.\n"
        f"const imageManifest = {body};\n\n"
        "export default imageManifest;\n"
    )


def main() -> None:
    folders = sys.argv[1:]
    if not folders:
        sys.exit(__doc__)

    existing = {}
    if MANIFEST.exists():
        text = MANIFEST.read_text()
        match = re.search(r"const imageManifest = (\{.*\});", text, re.S)
        if match:
            existing = json.loads(match.group(1))

    for folder in folders:
        entries = build_folder(folder)
        slug = slugify(folder.split("_", 1)[1] if "_" in folder else folder)
        existing[slug] = entries
        total = sum(
            (OUT_ROOT / slug / f"{e['id']}-{w}.webp").stat().st_size
            for e in entries
            for w in e["widths"]
        )
        print(
            f"{folder}: {len(entries)} images -> "
            f"{sum(len(e['widths']) for e in entries)} files, {total / 1e6:.1f} MB"
        )

    write_manifest(existing)
    print(f"manifest: {MANIFEST.relative_to(REPO)}")


if __name__ == "__main__":
    main()
